// src/train/data.js
// Curated MBTA rapid transit and commuter rail station data.
// No API required — update manually when the MBTA changes service.
//
// Each station has:
//   id         — unique within the line (used as a key)
//   name       — display name shown in the dropdown
//   signName   — (optional) what fills the sign; omit to use name directly
//               Used when the dropdown label includes a branch annotation
//               like "St. Paul Street (B Branch)" but the sign should say
//               just "St. Paul Street".

export const LINES = {
  red: {
    id: 'red',
    name: 'Red Line',
    headerColor: '#DA291C',
    defaultSubheader: 'RED LINE',
    stations: [
      { id: 'alewife',           name: 'Alewife' },
      { id: 'davis',             name: 'Davis' },
      { id: 'porter',            name: 'Porter' },
      { id: 'harvard',           name: 'Harvard' },
      { id: 'central',           name: 'Central' },
      { id: 'kendall-mit',       name: 'Kendall/MIT' },
      { id: 'charles-mgh',       name: 'Charles/MGH' },
      { id: 'park-street',       name: 'Park Street' },
      { id: 'downtown-crossing', name: 'Downtown Crossing' },
      { id: 'south-station',     name: 'South Station' },
      { id: 'broadway',          name: 'Broadway' },
      { id: 'andrew',            name: 'Andrew' },
      { id: 'jfk-umass',        name: 'JFK/UMass' },
      // Ashmont branch
      { id: 'savin-hill',        name: 'Savin Hill' },
      { id: 'fields-corner',     name: 'Fields Corner' },
      { id: 'shawmut',           name: 'Shawmut' },
      { id: 'ashmont',           name: 'Ashmont' },
      // Braintree branch
      { id: 'north-quincy',      name: 'North Quincy' },
      { id: 'wollaston',         name: 'Wollaston' },
      { id: 'quincy-center',     name: 'Quincy Center' },
      { id: 'quincy-adams',      name: 'Quincy Adams' },
      { id: 'braintree',         name: 'Braintree' },
    ],
  },

  orange: {
    id: 'orange',
    name: 'Orange Line',
    headerColor: '#ED8B00',
    defaultSubheader: 'ORANGE LINE',
    stations: [
      { id: 'oak-grove',         name: 'Oak Grove' },
      { id: 'malden-center',     name: 'Malden Center' },
      { id: 'wellington',        name: 'Wellington' },
      { id: 'assembly',          name: 'Assembly' },
      { id: 'sullivan-square',   name: 'Sullivan Square' },
      { id: 'community-college', name: 'Community College' },
      { id: 'north-station',     name: 'North Station' },
      { id: 'haymarket',         name: 'Haymarket' },
      { id: 'state',             name: 'State' },
      { id: 'downtown-crossing', name: 'Downtown Crossing' },
      { id: 'chinatown',         name: 'Chinatown' },
      { id: 'tufts-medical',     name: 'Tufts Medical Center' },
      { id: 'back-bay',          name: 'Back Bay' },
      { id: 'mass-ave',          name: 'Massachusetts Avenue' },
      { id: 'ruggles',           name: 'Ruggles' },
      { id: 'roxbury-crossing',  name: 'Roxbury Crossing' },
      { id: 'jackson-square',    name: 'Jackson Square' },
      { id: 'stony-brook',       name: 'Stony Brook' },
      { id: 'green-street',      name: 'Green Street' },
      { id: 'forest-hills',      name: 'Forest Hills' },
    ],
  },

  blue: {
    id: 'blue',
    name: 'Blue Line',
    headerColor: '#003DA5',
    defaultSubheader: 'BLUE LINE',
    stations: [
      { id: 'wonderland',        name: 'Wonderland' },
      { id: 'revere-beach',      name: 'Revere Beach' },
      { id: 'beachmont',         name: 'Beachmont' },
      { id: 'suffolk-downs',     name: 'Suffolk Downs' },
      { id: 'orient-heights',    name: 'Orient Heights' },
      { id: 'wood-island',       name: 'Wood Island' },
      { id: 'airport',           name: 'Airport' },
      { id: 'maverick',          name: 'Maverick' },
      { id: 'aquarium',          name: 'Aquarium' },
      { id: 'state',             name: 'State' },
      { id: 'government-center', name: 'Government Center' },
      { id: 'bowdoin',           name: 'Bowdoin' },
    ],
  },

  green: {
    id: 'green',
    name: 'Green Line',
    headerColor: '#00843D',
    defaultSubheader: 'GREEN LINE',
    stations: [
      // GLX Extension (north)
      { id: 'medford-tufts',         name: 'Medford/Tufts' },
      { id: 'ball-square',           name: 'Ball Square' },
      { id: 'magoun-square',         name: 'Magoun Square' },
      { id: 'gilman-square',         name: 'Gilman Square' },
      { id: 'east-somerville',       name: 'East Somerville' },
      { id: 'union-square',          name: 'Union Square' },
      // Main trunk (shared by all branches)
      { id: 'lechmere',              name: 'Lechmere' },
      { id: 'science-park',          name: 'Science Park/West End' },
      { id: 'north-station',         name: 'North Station' },
      { id: 'haymarket',             name: 'Haymarket' },
      { id: 'government-center',     name: 'Government Center' },
      { id: 'park-street',           name: 'Park Street' },
      { id: 'boylston',              name: 'Boylston' },
      { id: 'arlington',             name: 'Arlington' },
      { id: 'copley',                name: 'Copley' },
      // Shared by B, C, D (not E)
      { id: 'hynes',                 name: 'Hynes Convention Center' },
      { id: 'kenmore',               name: 'Kenmore' },
      // B Branch (Boston College)
      { id: 'blandford-st',          name: 'Blandford Street' },
      { id: 'bu-east',               name: 'BU East' },
      { id: 'bu-central',            name: 'BU Central' },
      { id: 'bu-west',               name: 'BU West' },
      { id: 'st-paul-b',             name: 'St. Paul Street (B Branch)', signName: 'St. Paul Street' },
      { id: 'pleasant-st',           name: 'Pleasant Street' },
      { id: 'babcock-st',            name: 'Babcock Street' },
      { id: 'packards-corner',       name: "Packard's Corner" },
      { id: 'harvard-ave',           name: 'Harvard Avenue' },
      { id: 'griggs-st',             name: 'Griggs Street' },
      { id: 'allston-st',            name: 'Allston Street' },
      { id: 'warren-st',             name: 'Warren Street' },
      { id: 'washington-st-b',       name: 'Washington Street (B Branch)', signName: 'Washington Street' },
      { id: 'sutherland-rd',         name: 'Sutherland Road' },
      { id: 'chestnut-hill-ave',     name: 'Chestnut Hill Avenue' },
      { id: 'south-st',              name: 'South Street' },
      { id: 'boston-college',        name: 'Boston College' },
      // C Branch (Cleveland Circle)
      { id: 'saint-marys-st',        name: "Saint Mary's Street" },
      { id: 'hawes-st',              name: 'Hawes Street' },
      { id: 'kent-st',               name: 'Kent Street' },
      { id: 'st-paul-c',             name: 'St. Paul Street (C Branch)', signName: 'St. Paul Street' },
      { id: 'coolidge-corner',       name: 'Coolidge Corner' },
      { id: 'summit-ave',            name: 'Summit Avenue' },
      { id: 'brandon-hall',          name: 'Brandon Hall' },
      { id: 'fairbanks-st',          name: 'Fairbanks Street' },
      { id: 'washington-sq',         name: 'Washington Square' },
      { id: 'tappan-st',             name: 'Tappan Street' },
      { id: 'dean-rd',               name: 'Dean Road' },
      { id: 'englewood-ave',         name: 'Englewood Avenue' },
      { id: 'cleveland-circle',      name: 'Cleveland Circle' },
      // D Branch (Riverside)
      { id: 'fenway',                name: 'Fenway' },
      { id: 'longwood-d',            name: 'Longwood' },
      { id: 'brookline-village',     name: 'Brookline Village' },
      { id: 'brookline-hills',       name: 'Brookline Hills' },
      { id: 'beaconsfield',          name: 'Beaconsfield' },
      { id: 'reservoir',             name: 'Reservoir' },
      { id: 'chestnut-hill-d',       name: 'Chestnut Hill' },
      { id: 'newton-centre',         name: 'Newton Centre' },
      { id: 'newton-highlands',      name: 'Newton Highlands' },
      { id: 'eliot',                 name: 'Eliot' },
      { id: 'waban',                 name: 'Waban' },
      { id: 'woodland',              name: 'Woodland' },
      { id: 'riverside',             name: 'Riverside' },
      // E Branch (Heath Street)
      { id: 'prudential',            name: 'Prudential' },
      { id: 'symphony',              name: 'Symphony' },
      { id: 'northeastern',          name: 'Northeastern' },
      { id: 'museum-fine-arts',      name: 'Museum of Fine Arts' },
      { id: 'longwood-medical',      name: 'Longwood Medical Area' },
      { id: 'brigham-circle',        name: 'Brigham Circle' },
      { id: 'fenwood-rd',            name: 'Fenwood Road' },
      { id: 'mission-park',          name: 'Mission Park' },
      { id: 'riverway',              name: 'Riverway' },
      { id: 'back-of-the-hill',      name: 'Back of the Hill' },
      { id: 'heath-st',              name: 'Heath Street' },
    ],
  },

  silver: {
    id: 'silver',
    name: 'Silver Line',
    headerColor: '#7C878E',
    defaultSubheader: 'SILVER LINE',
    stations: [
      { id: 'south-station',         name: 'South Station' },
      { id: 'courthouse',            name: 'Courthouse' },
      { id: 'world-trade-center',    name: 'World Trade Center' },
      { id: 'silver-line-way',       name: 'Silver Line Way' },
      { id: 'design-center',         name: 'Design Center' },
      { id: 'eastern-ave',           name: 'Eastern Avenue' },
      { id: 'box-district',          name: 'Box District' },
      { id: 'bellingham-sq',         name: 'Bellingham Square' },
      { id: 'chelsea',               name: 'Chelsea' },
      { id: 'terminal-a',            name: 'Terminal A' },
      { id: 'terminal-b',            name: 'Terminal B' },
      { id: 'terminal-c',            name: 'Terminal C' },
      { id: 'terminal-e',            name: 'Terminal E' },
    ],
  },

  commuter: {
    id: 'commuter',
    name: 'Commuter Rail',
    headerColor: '#80276C',
    defaultSubheader: 'COMMUTER RAIL',
    stations: [
      // Major hubs
      { id: 'north-station',         name: 'North Station' },
      { id: 'south-station',         name: 'South Station' },
      { id: 'back-bay',              name: 'Back Bay' },
      { id: 'ruggles',               name: 'Ruggles' },
      { id: 'forest-hills-cr',       name: 'Forest Hills', signName: 'Forest Hills' },
      { id: 'hyde-park',             name: 'Hyde Park' },
      { id: 'route-128',             name: 'Route 128' },
      { id: 'readville',             name: 'Readville' },
      // Fairmount Line
      { id: 'fairmount',             name: 'Fairmount' },
      { id: 'blue-hill-ave',         name: 'Blue Hill Avenue' },
      { id: 'morton-st',             name: 'Morton Street' },
      { id: 'talbot-ave',            name: 'Talbot Avenue' },
      { id: 'four-corners',          name: 'Four Corners/Geneva' },
      { id: 'uphams-corner',         name: "Uphams Corner" },
      // Providence/Stoughton Line
      { id: 'providence',            name: 'Providence' },
      { id: 'tf-green',              name: 'TF Green Airport' },
      { id: 'wickford-jct',          name: 'Wickford Junction' },
      { id: 'stoughton',             name: 'Stoughton' },
      // Needham Line
      { id: 'needham-heights',       name: 'Needham Heights' },
      { id: 'needham-center',        name: 'Needham Center' },
      { id: 'needham-junction',      name: 'Needham Junction' },
      // Franklin Line
      { id: 'franklin',              name: 'Franklin' },
      { id: 'forge-park',            name: 'Forge Park/495' },
      // Kingston/Plymouth Line
      { id: 'kingston',              name: 'Kingston' },
      { id: 'plymouth',              name: 'Plymouth' },
      // Middleborough/Lakeville Line
      { id: 'middleborough',         name: 'Middleborough/Lakeville' },
      // Greenbush Line
      { id: 'greenbush',             name: 'Greenbush' },
      { id: 'scituate',              name: 'Scituate' },
      // Lowell Line
      { id: 'lowell',                name: 'Lowell' },
      { id: 'anderson-woburn',       name: 'Anderson/Woburn' },
      // Haverhill Line
      { id: 'haverhill',             name: 'Haverhill' },
      { id: 'lawrence',              name: 'Lawrence' },
      { id: 'andover',               name: 'Andover' },
      // Newburyport/Rockport Line
      { id: 'newburyport',           name: 'Newburyport' },
      { id: 'rockport',              name: 'Rockport' },
      { id: 'gloucester',            name: 'Gloucester' },
      { id: 'salem',                 name: 'Salem' },
      { id: 'beverly',               name: 'Beverly' },
      { id: 'lynn',                  name: 'Lynn' },
      { id: 'chelsea-cr',            name: 'Chelsea', signName: 'Chelsea' },
      // Fitchburg Line
      { id: 'fitchburg',             name: 'Fitchburg' },
      { id: 'wachusett',             name: 'Wachusett' },
      { id: 'ayer',                  name: 'Ayer' },
      { id: 'concord',               name: 'Concord' },
      { id: 'acton',                 name: 'Acton' },
      // Worcester Line
      { id: 'worcester',             name: 'Worcester' },
      { id: 'framingham',            name: 'Framingham' },
      { id: 'natick',                name: 'Natick' },
      { id: 'wellesley-sq',          name: 'Wellesley Square' },
      { id: 'auburndale',            name: 'Auburndale' },
      { id: 'newtonville',           name: 'Newtonville' },
      { id: 'west-newton',           name: 'West Newton' },
    ],
  },
};
